version: 1.2
name: kleborate-ecoli
description: |
  Dockerized version of Kleborate v3.2.1 with extended support for *Escherichia coli*.
  This image enables rapid typing and profiling of both *Klebsiella* and *E. coli* genomes,
  including detection of antimicrobial resistance (AMR) genes, virulence loci, and sequence types.
  Designed for reproducibility and portability in bioinformatics workflows.

  Based on the official Kleborate tool and pre-configured for easy use in containerized environments.

toolname: kleborate-ecoli

tools:
  - subclass: docker
    name: kleborate-ecoli
    namespace: efosternyarko
    registry: dockerhub
    registry_path: myebenn/kleborate
    primaryDescriptorPath: /Dockerfile
    descriptorType: docker
    authors:
      - name: Mary Maranga

